version: "3"

networks:
  macvlan_network:
    name: lab_macvlan
    driver: macvlan
    enable_ipv6: false
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.240/28
  
  internalbr:
    name: lab_bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
          ip_range: 192.168.10.240/28

secrets:
  config_json:
    file: secrets.json

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    networks:
      macvlan_network:
        ipv4_address: 192.168.1.254
      internalbr:
        ipv4_address: 192.168.10.254
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Moscow
    volumes:
      - /volume1/docker/adguard/work:/opt/adguardhome/work
      - /volume1/docker/adguard/conf:/opt/adguardhome/conf
      - /volume1/acme/certs:/certs
    restart: unless-stopped

  unifi:
    image: jacobalberty/unifi:latest
    container_name: unifi
    network_mode: "host"
    environment:
      - UNIFI_UID=1026
      - UNIFI_GID=100
      - BIND_PRIV=false
      - RUNAS_UID0=false
      - TZ=Europe/Moscow
    volumes:
      - /volume1/docker/unifi:/unifi
    restart: unless-stopped

  foundryvtt:
    image: felddy/foundryvtt:latest
    container_name: foundry
    network_mode: "host"
    environment:
      - FOUNDRY_UID=1026
      - FOUNDRY_GID=100
      - TIMEZONE=Europe/Moscow
    volumes:
      - /volume1/docker/foundryvtt:/data
    secrets:
      - source: config_json
        target: config.json
    restart: unless-stopped
